# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 07:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='functions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
