# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deepgo', '0003_auto_20160623_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('data_format', models.CharField(choices=[('enter', 'Splitted by enters'), ('fasta', 'FASTA')], max_length=10)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prediction_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.AddField(
            model_name='prediction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='deepgo.PredictionGroup'),
        ),
    ]
