# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0005_auto_20170601_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiongroup',
            name='data_format',
            field=models.CharField(choices=[('enter', 'Raw Sequence'), ('fasta', 'FASTA')], default='fasta', max_length=10),
        ),
    ]
