# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-09 09:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0006_auto_20170601_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_accession', models.CharField(max_length=16, unique=True)),
                ('uni_entry_id', models.CharField(max_length=16, unique=True)),
                ('sequence', models.TextField()),
                ('sequence_md5', models.CharField(db_index=True, max_length=32)),
                ('ppi_embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
