# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 18:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0008_predictiongroup_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiongroup',
            name='threshold',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
