# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-01 07:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0009_auto_20170822_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='functions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None),
        ),
    ]
