# Generated by Django 2.1.7 on 2019-05-05 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0011_auto_20190415_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiongroup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
