# Generated by Django 2.2.4 on 2019-09-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0012_auto_20190505_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.RemoveField(
            model_name='protein',
            name='ppi_embedding',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='sequence_md5',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='uni_accession',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='uni_entry_id',
        ),
        migrations.AddField(
            model_name='protein',
            name='acc_id',
            field=models.CharField(default='PROTEIN', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='gene',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='name',
            field=models.CharField(default='name', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='pro_id',
            field=models.CharField(db_index=True, default='PROTEIN', max_length=31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='protein',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_id', models.PositiveIntegerField(db_index=True)),
                ('score', models.PositiveIntegerField()),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='deepgo.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proteins', to='deepgo.Taxonomy'),
        ),
    ]
