# Generated by Django 2.2.4 on 2019-09-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0013_auto_20190902_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
