# Generated by Django 2.2.4 on 2019-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0014_auto_20190902_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
