# Generated by Django 2.2.4 on 2019-09-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0018_auto_20190902_1229'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='protein',
            index_together={('id', 'taxon')},
        ),
    ]
