# Generated by Django 2.1.7 on 2020-11-16 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0020_prediction_similar_proteins'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiongroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, editable=False),
        ),
    ]
