# Generated by Django 2.1.7 on 2020-11-16 06:52

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    pg = apps.get_model('deepgo', 'PredictionGroup')
    for row in pg.objects.all():
        row.uuid = uuid.uuid4()
        row.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0021_predictiongroup_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
