# Generated by Django 2.1.7 on 2020-11-26 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0024_prediction_similar_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=15, unique=True)),
                ('notes', models.TextField()),
                ('data_root', models.FilePathField(allow_files=False, allow_folders=True, path='data/')),
                ('alpha_bp', models.FloatField(default=0.59, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('alpha_mf', models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('alpha_cc', models.FloatField(default=0.46, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='protein',
        ),
        migrations.AlterIndexTogether(
            name='protein',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='protein',
            name='taxon',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
        migrations.DeleteModel(
            name='Taxonomy',
        ),
        migrations.AddField(
            model_name='predictiongroup',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_groups', to='deepgo.Release'),
        ),
    ]
