# Generated by Django 2.1.7 on 2020-12-07 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0025_auto_20201126_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
