# Generated by Django 4.2.16 on 2026-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0026_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='data_root',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/opt-data/extracted/'),
        ),
    ]
