# Generated by Django 4.2.30 on 2026-06-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0027_alter_release_data_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictiongroup',
            name='predictor',
            field=models.CharField(choices=[('deepgoplus', 'DeepGOPlus (CNN + DIAMOND)'), ('dgpp-light', 'DeepGO-PlusPlus-Light, hierarchy-aware CNN (CPU)')], default='deepgoplus', max_length=20),
        ),
    ]
