# Generated by Django 4.2.30 on 2026-07-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepgo', '0036_alter_predictiongroup_predictor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiongroup',
            name='predictor',
            field=models.CharField(
                choices=[
                    ('deepgoplus', 'DeepGOPlus (CNN + DIAMOND)'),
                    (
                        'dgpp-light',
                        'DeepGO-PlusPlus-Light — multi-evidence ensemble '
                        '(DIAMOND + STRING-Net + hierarchy-aware CNN + ESM2-kNN + ProteInfer)',
                    ),
                ],
                default='deepgoplus',
                max_length=20,
            ),
        ),
    ]
